baseURL = 'https://emcybertrack.com'
languageCode = 'en-us'
title = 'EM cybertrack'
theme = 'PaperMod'

[caches]
[caches.images]
dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true

[params]
customCSS = [
    "css/extended/theme-vars-override.css",
    "css/extended/header-custom.css",
    "css/extended/about-page.css",
]
disableThemeToggle = true

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 3

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 4

[[menu.main]]
name = "Tips"
url = "/tips/"
weight = 5

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/eliel-monfort/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/eliel-monfort/"

[[params.socialIcons]]
name = "hackthebox"
url = "https://app.hackthebox.com/profile/2083370"

[[params.socialIcons]]
name = "tryhackme"
url = "https://tryhackme.com/p/Eliel.M/"

[params.homeInfoParams]
Title = "Hello."
Content = """
**Welcome to EM cybertrack** - my cybersecurity learning website.  
Here you'll find my certifications, hands-on projects, CTF WriteUps, study notes, and blog posts documenting  
my journey in cybersecurity.  
<br>
Whether you're hiring, learning, or exploring, everything is open for you to discover.  
If you’re new here, please check the **[about me](https://emcybertrack.com/about/)** page.  
<br>
-- Eliel Monfort
"""
